"""Seed catalog of well-known games for GameScout."""

GAMES_SEED = [
    {
        "game_id": "zelda-totk",
        "title": "The Legend of Zelda: Tears of the Kingdom",
        "cover": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Aventura", "Ação", "Mundo Aberto"],
        "platforms": ["switch"],
        "developer": "Nintendo EPD",
        "description": "Sequela direta de Breath of the Wild, com construção de veículos e exploração vertical em Hyrule.",
    },
    {
        "game_id": "elden-ring",
        "title": "Elden Ring",
        "cover": "https://images.unsplash.com/photo-1612404730960-5c71577fca11?w=600&h=800&fit=crop",
        "year": 2022,
        "genres": ["RPG", "Ação", "Souls-like"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x"],
        "developer": "FromSoftware",
        "description": "Um mundo aberto desenhado por Hidetaka Miyazaki e George R. R. Martin.",
    },
    {
        "game_id": "gta-v",
        "title": "Grand Theft Auto V",
        "cover": "https://images.unsplash.com/photo-1605899435973-ca2d1a8431cf?w=600&h=800&fit=crop",
        "year": 2013,
        "genres": ["Ação", "Mundo Aberto"],
        "platforms": ["pc", "ps3", "ps4", "ps5", "xbox-360", "xbox-one", "xbox-series-x"],
        "developer": "Rockstar Games",
        "description": "Três protagonistas, uma cidade enorme, infinitas possibilidades em Los Santos.",
    },
    {
        "game_id": "minecraft",
        "title": "Minecraft",
        "cover": "https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600&h=800&fit=crop",
        "year": 2011,
        "genres": ["Sandbox", "Sobrevivência"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x", "switch", "mobile"],
        "developer": "Mojang",
        "description": "Construa, explore, sobreviva — o sandbox de blocos mais vendido de sempre.",
    },
    {
        "game_id": "rdr2",
        "title": "Red Dead Redemption 2",
        "cover": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=600&h=800&fit=crop",
        "year": 2018,
        "genres": ["Ação", "Mundo Aberto", "Western"],
        "platforms": ["pc", "ps4", "xbox-one"],
        "developer": "Rockstar Games",
        "description": "Arthur Morgan e a gangue Van der Linde no fim da era do Velho Oeste.",
    },
    {
        "game_id": "witcher-3",
        "title": "The Witcher 3: Wild Hunt",
        "cover": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=800&fit=crop&sat=-100",
        "year": 2015,
        "genres": ["RPG", "Fantasia"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x", "switch"],
        "developer": "CD Projekt Red",
        "description": "Geralt de Rivia em busca de Ciri num mundo medieval e brutal.",
    },
    {
        "game_id": "bg3",
        "title": "Baldur's Gate 3",
        "cover": "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["RPG", "D&D", "Tático"],
        "platforms": ["pc", "ps5", "xbox-series-x"],
        "developer": "Larian Studios",
        "description": "Uma das maiores RPGs de sempre, baseada em Dungeons & Dragons.",
    },
    {
        "game_id": "spider-man-2",
        "title": "Marvel's Spider-Man 2",
        "cover": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Ação", "Super-Heróis"],
        "platforms": ["ps5"],
        "developer": "Insomniac Games",
        "description": "Peter e Miles enfrentam Venom em Nova Iorque.",
    },
    {
        "game_id": "hogwarts-legacy",
        "title": "Hogwarts Legacy",
        "cover": "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["RPG", "Fantasia", "Mundo Aberto"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x", "switch"],
        "developer": "Avalanche Software",
        "description": "Vive uma aventura no século XIX no mundo de Harry Potter.",
    },
    {
        "game_id": "totk",
        "title": "Totk Companion",
        "cover": "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=800&fit=crop",
        "year": 2024,
        "genres": ["Aventura"],
        "platforms": ["pc"],
        "developer": "Indie",
        "description": "Companhia comunitária para fãs.",
    },
    {
        "game_id": "ff16",
        "title": "Final Fantasy XVI",
        "cover": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["RPG", "Ação", "Fantasia"],
        "platforms": ["ps5", "pc"],
        "developer": "Square Enix",
        "description": "Clive Rosfield e os Eikons num conflito épico em Valisthea.",
    },
    {
        "game_id": "resident-evil-4-r",
        "title": "Resident Evil 4 Remake",
        "cover": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Terror", "Ação", "Sobrevivência"],
        "platforms": ["pc", "ps4", "ps5", "xbox-series-x"],
        "developer": "Capcom",
        "description": "Leon S. Kennedy regressa numa reimaginação brutal do clássico.",
    },
    {
        "game_id": "silent-hill-2-r",
        "title": "Silent Hill 2 Remake",
        "cover": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=600&h=800&fit=crop&sat=-50",
        "year": 2024,
        "genres": ["Terror", "Psicológico"],
        "platforms": ["pc", "ps5"],
        "developer": "Bloober Team",
        "description": "James Sunderland regressa à cidade do nevoeiro.",
    },
    {
        "game_id": "alan-wake-2",
        "title": "Alan Wake 2",
        "cover": "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Terror", "Suspense"],
        "platforms": ["pc", "ps5", "xbox-series-x"],
        "developer": "Remedy Entertainment",
        "description": "Um escritor preso num pesadelo. Sequela aclamada de Alan Wake.",
    },
    {
        "game_id": "phasmophobia",
        "title": "Phasmophobia",
        "cover": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=600&h=800&fit=crop&sat=-100",
        "year": 2020,
        "genres": ["Terror", "Coop", "Indie"],
        "platforms": ["pc"],
        "developer": "Kinetic Games",
        "description": "Caça a fantasmas cooperativa em VR ou desktop.",
    },
    {
        "game_id": "cyberpunk-2077",
        "title": "Cyberpunk 2077",
        "cover": "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&h=800&fit=crop&sat=-30",
        "year": 2020,
        "genres": ["RPG", "Ação", "Sci-Fi"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x"],
        "developer": "CD Projekt Red",
        "description": "Night City em todo o seu esplendor neon depois das atualizações.",
    },
    {
        "game_id": "horizon-fw",
        "title": "Horizon Forbidden West",
        "cover": "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=600&h=800&fit=crop",
        "year": 2022,
        "genres": ["RPG", "Ação", "Mundo Aberto"],
        "platforms": ["ps4", "ps5", "pc"],
        "developer": "Guerrilla Games",
        "description": "Aloy explora o oeste pós-apocalíptico cheio de máquinas.",
    },
    {
        "game_id": "god-of-war-r",
        "title": "God of War Ragnarök",
        "cover": "https://images.unsplash.com/photo-1556438064-2d7646166914?w=600&h=800&fit=crop",
        "year": 2022,
        "genres": ["Ação", "Aventura", "Mitologia"],
        "platforms": ["ps4", "ps5", "pc"],
        "developer": "Santa Monica Studio",
        "description": "Kratos e Atreus enfrentam o fim dos deuses nórdicos.",
    },
    {
        "game_id": "fifa-24",
        "title": "EA Sports FC 24",
        "cover": "https://images.unsplash.com/photo-1614632537190-23e4146777db?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Desporto", "Futebol"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x", "switch"],
        "developer": "EA Sports",
        "description": "O sucessor do FIFA, com a liga portuguesa e clubes de topo.",
    },
    {
        "game_id": "valorant",
        "title": "Valorant",
        "cover": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=800&fit=crop&sat=-80",
        "year": 2020,
        "genres": ["FPS", "Tático", "Multijogador"],
        "platforms": ["pc"],
        "developer": "Riot Games",
        "description": "Tático 5v5 com agentes únicos da Riot.",
    },
    {
        "game_id": "lol",
        "title": "League of Legends",
        "cover": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&h=800&fit=crop",
        "year": 2009,
        "genres": ["MOBA", "Multijogador"],
        "platforms": ["pc"],
        "developer": "Riot Games",
        "description": "O MOBA mais jogado do mundo.",
    },
    {
        "game_id": "fortnite",
        "title": "Fortnite",
        "cover": "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=600&h=800&fit=crop&sat=-30",
        "year": 2017,
        "genres": ["Battle Royale", "Sandbox"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "xbox-series-x", "switch", "mobile"],
        "developer": "Epic Games",
        "description": "Battle royale com construção e crossover constante.",
    },
    {
        "game_id": "starfield",
        "title": "Starfield",
        "cover": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["RPG", "Sci-Fi", "Mundo Aberto"],
        "platforms": ["pc", "xbox-series-x"],
        "developer": "Bethesda Game Studios",
        "description": "Explora 1000 planetas no novo RPG espacial da Bethesda.",
    },
    {
        "game_id": "stardew-valley",
        "title": "Stardew Valley",
        "cover": "https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=600&h=800&fit=crop",
        "year": 2016,
        "genres": ["Indie", "Simulação", "RPG"],
        "platforms": ["pc", "ps4", "xbox-one", "switch", "mobile"],
        "developer": "ConcernedApe",
        "description": "Cultiva, pesca, casa e vive numa quinta encantadora.",
    },
    {
        "game_id": "hades",
        "title": "Hades",
        "cover": "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600&h=800&fit=crop",
        "year": 2020,
        "genres": ["Roguelike", "Ação", "Indie"],
        "platforms": ["pc", "ps4", "ps5", "xbox-one", "switch"],
        "developer": "Supergiant Games",
        "description": "Zagreus tenta escapar do submundo no roguelike mais elogiado.",
    },
    {
        "game_id": "celeste",
        "title": "Celeste",
        "cover": "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&h=800&fit=crop",
        "year": 2018,
        "genres": ["Plataformas", "Indie"],
        "platforms": ["pc", "ps4", "xbox-one", "switch"],
        "developer": "Maddy Makes Games",
        "description": "Um plataformas precisa sobre escalar uma montanha — e a saúde mental.",
    },
    {
        "game_id": "cs2",
        "title": "Counter-Strike 2",
        "cover": "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["FPS", "Multijogador", "Tático"],
        "platforms": ["pc"],
        "developer": "Valve",
        "description": "A nova geração do tático 5v5 mais antigo do mundo.",
    },
    {
        "game_id": "dota-2",
        "title": "Dota 2",
        "cover": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&h=800&fit=crop&sat=-50",
        "year": 2013,
        "genres": ["MOBA", "Multijogador"],
        "platforms": ["pc"],
        "developer": "Valve",
        "description": "MOBA hardcore com milhões em prémios.",
    },
    {
        "game_id": "fc-mobile",
        "title": "EA Sports FC Mobile",
        "cover": "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=600&h=800&fit=crop",
        "year": 2023,
        "genres": ["Desporto", "Futebol"],
        "platforms": ["mobile"],
        "developer": "EA Sports",
        "description": "Futebol completo no telemóvel.",
    },
    {
        "game_id": "lethal-company",
        "title": "Lethal Company",
        "cover": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&h=800&fit=crop&sat=-30",
        "year": 2023,
        "genres": ["Coop", "Terror", "Indie"],
        "platforms": ["pc"],
        "developer": "Zeekerss",
        "description": "Recolhe sucata em luas perigosas com amigos.",
    },
    {
        "game_id": "tekken-8",
        "title": "Tekken 8",
        "cover": "https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=600&h=800&fit=crop&sat=-30",
        "year": 2024,
        "genres": ["Luta"],
        "platforms": ["pc", "ps5", "xbox-series-x"],
        "developer": "Bandai Namco",
        "description": "A saga Mishima continua na nova geração.",
    },
]
